c_compiler:
  - gcc
cxx_compiler:
  - gxx
fortran_compiler:
  - gfortran

c_compiler_version:  
  - 5 # [linux]
cxx_compiler_version:
  - 5 # [linux]
fortran_compiler_version:
  - 5 # [linux]

c_stdlib:
  - sysroot # [linux]
  - macosx_deployment_target # [osx]

macosx_deployment_target:   
  - 12.0 # [osx]

libgcc-ng:   
  - 5.* # [linux]
libstdcxx-ng:
  - 5.* # [linux]
libgomp:     
  - 5.* # [linux]
