c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 11.0                       # [osx]  

c_compiler_version:
  - 8 # [linux]
cxx_compiler_version:
  - 8 # [linux]
