# === Compilers (Linux) ===
c_compiler:            # [linux]
  - gcc
cxx_compiler:          # [linux]
  - gxx
fortran_compiler:      # [linux]
  - gfortran

c_compiler_version:    # [linux]
  - 5
cxx_compiler_version:  # [linux]
  - 5
fortran_compiler_version:  # [linux]
  - 5

# === C stdlib baseline (ABI floor) ===
c_stdlib:
  - sysroot                  # [linux]
  - macosx_deployment_target # [osx]

# macOS min runtime
macosx_deployment_target:   # [osx]
  - 12.0

# === Pin Linux runtimes to the SAME minor as compiler ===
# These variant pins ensure your build links against exactly 15.1.*
libgcc-ng:     # [linux]
  - 5.*
libstdcxx-ng:  # [linux]
  - 5.*
libgomp:       # [linux]
  - 5.*
